export interface eBavelField {  
  type : string;
  description : string;
}

export const eBavelFieldsTypes:eBavelField[] = [
  {type:'action', description:'Action'},
  {type:'alphanumeric', description:'Alphanumeric'},
  {type:'audio', description:'Audio'},
  {type:'calculatedField', description:'Calculated Field'},
  {type:'chart', description:'Chart'},
  {type:'date', description:'Date'},
  {type:'datetime', description:'Datetime'},
  {type:'detailView', description:'Detail View'},
  {type:'document', description:'Document'},
  {type:'email', description:'Email'},
  {type:'geolocation', description:'Geolocation'},
  {type:'html', description:'Html'},
  {type:'integer', description:'Integer'},
  {type:'password', description:'Password'},
  {type:'phone', description:'Phone'},
  {type:'photo', description:'Photo'},
  {type:'quickResponse', description:'Quick Response'},
  {type:'rating', description:'Rating'},
  {type:'report', description:'Report'},
  {type:'richText', description:'Rich Text'},
  {type:'sectionHeaderTitle', description:'Section Header Title'},
  {type:'signature', description:'Signature'},
  {type:'singleChoiceHorizontal', description:'Single Choice Horizontal'},
  {type:'singleChoiceList', description:'Single Choice List'},
  {type:'singleChoiceVertical', description:'Single Choice Vertical'},
  {type:'text', description:'Text'},
  {type:'time', description:'Time'},
  {type:'toggleSwitch', description:'Toggle Switch'},
  {type:'uniqueID', description:'UniqueID'},
  {type:'url', description:'Url'},
  {type:'video', description:'Video'},
]

export const eBavelFieldsTypes_:Record<string, string> = {
  'action' : 'Action',
  'alphanumeric' : 'Alphanumeric',
  'audio' : 'Audio',
  'calculatedField' : 'Calculated Field',
  'chart' : 'Chart',
  'date' : 'Date',
  'datetime' : 'Datetime',
  'detailView' : 'Detail View',
  'document' : 'Document',
  'email' : 'Email',
  'geolocation' : 'Geolocation',
  'html' : 'Html',
  'integer' : 'Integer',
  'password' : 'Password',
  'phone' : 'Phone',
  'photo' : 'Photo',
  'quickResponse' : 'Quick Response',
  'rating' : 'Rating',
  'report' : 'Report',
  'richText' : 'Rich Text',
  'sectionHeaderTitle' : 'Section Header Title',
  'signature' : 'Signature',
  'singleChoiceHorizontal' : 'Single Choice Horizontal',
  'singleChoiceList' : 'Single Choice List',
  'singleChoiceVertical' : 'Single Choice Vertical',
  'text' : 'Text',
  'time' : 'Time',
  'toggleSwitch' : 'Toggle Switch',
  'uniqueID' : 'UniqueID',
  'url' : 'Url',
  'video' : 'Video'
}
